#!/bin/sh

LIVE_BRANCH="__LIVE__"

if test -n "$1"; then
    local="$1"
else
    local=$(git config --get fai.local)
    if test -z "$local"; then
        local=local
    fi
fi

git branch -m "$LIVE_BRANCH" "$LIVE_BRANCH$(date +%Y%m%d-%H%M%S)"
git checkout -b "$LIVE_BRANCH"

for branch in ${local} puppet; do

    lb=$(git branch | grep  "^[[:space:]]*${branch}\$")
    if test -z "${lb}"; then
	echo "Branch ${branch} not found. Not merging. Hope that is OK."
    else
	git merge "${branch}"
    fi
done

