#!/bin/sh

LIVE_BRANCH="__LIVE__"

if test -n "$1"; then
    local="$1"
else
    local=local
fi

git branch -m "$LIVE_BRANCH" "$LIVE_BRANCH$(date +%Y%m%d-%H%M%S)"
git checkout -b "$LIVE_BRANCH"
git merge "$local"
