#!/bin/bash

DST=`pwd`
SRC=`pwd`/local.d

RET=

function rel_path () {
    local src="$1"
    local dst="$2"
    RET=$(python -c \
	'import sys; import os; print (os.path.relpath(sys.argv[1], sys.argv[2]))' \
	"${src}" "${dst}")
}

if ! test -d "${SRC}"; then
    exit 0
fi

cd ${SRC}

exclude=${DST}/.git/info/exclude


rm -fv "${exclude}"
for f in $(git ls-files); do
    d=$(dirname ${f})
    fn=$(basename "${f}")
    # Create destination directory if needed.
    dst_d=${DST}/${d}
    test -d ${dst_d} || mkdir -p ${dst_d}

    rel_path ${SRC}/${d} ${DST}/${d}
    relative_path="${RET}/${fn}"

    cd "${dst_d}"
    ln -nf "${relative_path}" "${dst_d}/${fn}"
    echo "${f}" >> "${exclude}"
done
