#!/bin/sh

if [ "$1" = "fail-debconf" ]; then
	. /usr/share/debconf/confmodule
	db_subst etckeeper/commit_failed VCS "$VCS"
	db_input critical etckeeper/commit_failed || true
	db_go || true
	db_reset etckeeper/commit_failed || true
	exit 0
fi

if etckeeper unclean; then
	if [ "$AVOID_COMMIT_BEFORE_INSTALL" = 1 ]; then
		echo "" >&2
		echo "** etckeeper detected uncommitted changes in /etc prior to $HIGHLEVEL_PACKAGE_MANAGER run" >&2 
		echo "** Aborting $HIGHLEVEL_PACKAGE_MANAGER run. Manually commit and restart." >&2
		echo "" >&2
		exit 1
	fi
	message="saving uncommitted changes in /etc prior to $HIGHLEVEL_PACKAGE_MANAGER run"
        installed=$(etckeeper list-installed | diff -U0 /etc/etckeeper/packagelist - | tail -n+4 | egrep '^[-+]' || true)
	if [ -n "${installed}" ]; then
	    message="$message

Package that might have been manually installed:

$installed"
	fi

	if ! etckeeper commit "$message"; then
		if [ -e /usr/share/debconf/confmodule ]; then
			$0 fail-debconf
		else
			echo "error: etckeeper failed to commit changes in /etc using $VCS"
			exit 1
		fi
	fi
fi
set +x

