#!/bin/sh

if test -d /var/lib/puppet; then

    rsync -ai --delete /var/lib/puppet $FAI_ROOT/tmp

    # Run puppet in a standlone mode.
    cat <<EOF | $ROOTCMD sh -
if test -d /tmp/puppet; then
    puppet apply --statedir /tmp/state --reportdir /tmp/reports \
        --modulepath /tmp/puppet/modules /tmp/puppet/manifests/site.pp
fi
EOF

fi

