#!/bin/bash

# assign classes to hosts
ifclass PRE_BASE || echo PRE_BASE

# use a list of classes for our demo machine
case $HOSTNAME in
    fai|fai2)
	echo "BASE DEBIAN LVM_SMALL FAI";;
    desktop)
	echo "BASE DEBIAN LVM_XFS X WIFI NVIDIA" ;;
    *)
	echo "BASE DEBIAN LVM_XFS";;
esac


for d in $disklist; do
    gb=$(parted /dev/$d unit GB print | awk '{if($1=="Disk"){print $NF}}' | cut -f1 -d. | cut -f1 -dG)
    if test  $gb -lt 24; then
	echo LVM_XFS_SMALL
    else
	echo LVM_XFS
    fi
exit 0
